[type:refactor] refactor some trie ruler codes.
apache/shenyu pull request #4414
Opened 2023-02-27 10:37 UTC by damonxue

Refactor some trie ruler codes.

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

2023-02-27 11:52 UTC, moremind requested changes

2023-02-27 11:52 UTC, moremind commented on shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
> -                        final List<RuleData> collect = ruleDataList.stream().sorted(Comparator.comparing(RuleData::getSort)).collect(Collectors.toList());
It's not good for using cow list.

2023-02-27 12:19 UTC, damonxue commented on shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
> -                        final List<RuleData> collect = ruleDataList.stream().sorted(Comparator.comparing(RuleData::getSort)).collect(Collectors.toList());
used CopyOnWriteArrayList;

2023-03-01 01:04 UTC, moremind requested changes

2023-03-01 01:04 UTC, moremind commented on shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
> +        if (CollectionUtils.isNotEmpty(uriPaths)) {
I don't think it's good.

2023-03-01 01:04 UTC, moremind commented on shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
> +                        if ((endPath || (isMatchAll(currentNode.getMatchStr()) && currentNode.getEndOfPath()))
endPath is not right.

2023-03-01 03:04 UTC, damonxue commented on shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/trie/ShenyuTrieTest.java
> +    public void matchSpec() {
Pls review covers all situations.

2023-03-01 05:22 UTC, moremind submitted a review, later dismissed

2023-03-01 05:33 UTC, moremind approved these changes

2023-03-01 07:31 UTC, merged