Optimize Trie code and improve wildcard * support
apache/shenyu pull request #4569
Opened 2023-04-18 08:53 UTC by lan-dian

Optimize Trie code and improve wildcard * support，such as *.html，*.jpg , or even *Shen*Yu.

Make sure that:

- [  ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [  ] You submit test cases (unit or integration tests) that back your changes.
- [  ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

2023-04-18 09:19 UTC, moremind requested changes

2023-04-18 09:19 UTC, moremind commented on shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
> +        if (matchMode == TrieMatchModeEnum.PATH_PATTERN) {
not use ==, use equals

2023-04-18 09:43 UTC, lan-dian commented on shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
> +        if (matchMode == TrieMatchModeEnum.PATH_PATTERN) {
Thanks. I have fixed the problem 😃

2023-04-19 01:28 UTC, lan-dian commented on shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
> +                checkAccess(matchAll, currentNode, startIndex, MATCH_ALL, pathPart);
finished

2023-04-19 12:43 UTC, moremind approved these changes

2023-04-19 12:43 UTC, merged