feature shenyu-plugin:add shenyu-plugin-logging-huawei-lts
apache/shenyu pull request #4812
Opened 2023-07-06 07:25 UTC by xcsnx

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

2023-07-06 12:49 UTC, moremind approved these changes

2023-07-06 12:49 UTC, moremind commented on shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-huawei-lts/pom.xml
> +            <version>1.0.1</version>
use common properties

2023-07-06 12:49 UTC, moremind commented on shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-huawei-lts/src/main/java/org/apache/shenyu/plugin/huawei/lts/client/HuaweiLtsLogCollectClient.java
> +                // 华为云帐号的项目ID（project id）
use english comment

2023-07-06 12:49 UTC, moremind commented on shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-huawei-lts/src/main/java/org/apache/shenyu/plugin/huawei/lts/client/HuaweiLtsLogCollectClient.java
> +                // 重试的最大退避时间
same

2023-07-06 12:49 UTC, moremind commented on shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-huawei-lts/src/main/java/org/apache/shenyu/plugin/huawei/lts/client/HuaweiLtsLogCollectClient.java
> +            throw new RuntimeException(e);
not throw runtime exception

2023-07-06 12:49 UTC, moremind commented on shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-huawei-lts/src/test/java/org/apache/shenyu/plugin/huawei/lts/handler/LoggingHuaweiLtsPluginDataHandlerTest.java
> +                + "    \"logStreamId\": \"8b4fe176-4a7e-4bd5-8bb7-17d0ec6730b2\",\n"
use your accessId and secret key

2023-07-06 12:52 UTC, moremind requested changes

2023-07-06 12:52 UTC, moremind commented on shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-huawei-lts/src/main/java/org/apache/shenyu/plugin/huawei/lts/client/HuaweiLtsLogCollectClient.java
> +                // producer发送单批日志条数上限
not comment with .

2023-07-07 01:04 UTC, moremind requested changes

2023-07-07 01:04 UTC, moremind commented on shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-logging-huawei-lts/src/test/java/org/apache/shenyu/springboot/starter/plugin/logging/huawei/lts/LoggingTencentClsPluginConfigurationTest.java
> +public class LoggingTencentClsPluginConfigurationTest {
cls？

2023-07-07 02:24 UTC, xcsnx commented on shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-logging-huawei-lts/src/test/java/org/apache/shenyu/springboot/starter/plugin/logging/huawei/lts/LoggingTencentClsPluginConfigurationTest.java
> +public class LoggingTencentClsPluginConfigurationTest {
Thanks, I will improve the code

2023-07-11 06:06 UTC, yunlongn commented
pls add data.  -> `./db/upgrade/2.5.1-upgrade-2.6.0-*.sql`

2023-07-11 06:54 UTC, xcsnx commented
> pls add data. -> `./db/upgrade/2.5.1-upgrade-2.6.0-*.sql` @xcsnx
ok

2023-07-13 13:25 UTC, moremind approved these changes

2023-07-13 13:25 UTC, merged