[type:fix] Polish Code.
apache/shenyu pull request #4945
Opened 2023-08-02 05:19 UTC by GOODBOY008

[type:fix] Polish Code.

2023-08-02 06:11 UTC, dragon-zhang commented
Hi, please check CI

2023-08-02 07:36 UTC, moremind requested changes

2023-08-02 07:36 UTC, moremind commented on shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperClient.java
> +        if (listeners != null) {
use Objects.isNull

2023-08-02 07:36 UTC, moremind commented on shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-zookeeper/src/main/java/org/apache/shenyu/register/client/server/zookeeper/ZookeeperClient.java
> +        if (listeners != null) {
use Objects.isNull

2023-08-02 07:36 UTC, moremind commented on shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClient.java
> +        if (listeners != null) {
Objects.isNull

2023-08-03 07:23 UTC, moremind submitted a review, later dismissed

2023-08-03 08:57 UTC, moremind commented
@GOODBOY008 Hi, pls check ci

2023-08-03 09:32 UTC, moremind approved these changes

2023-08-03 10:29 UTC, merged