Support `isBlank`
apache/shenyu pull request #4983
Opened 2023-08-10 06:13 UTC by kerwin612

Added `BlankPredicateJudge` class to support `isBlank` predicate

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

2023-08-11 15:22 UTC, kerwin612 commented
Can anyone respond to this PR? I created it in version 2.6.0, but now it's 2.6.1. :joy:

2023-08-14 15:09 UTC, moremind commented
copy new sql named 2.6.1 from 2.6.0.sql, and add these fields to 2.6.1.sql and 2.6.0-to-2.6.1.sql

2023-08-14 15:09 UTC, moremind requested changes

2023-08-15 00:40 UTC, moremind commented on db/upgrade/2.6.0-upgrade-2.6.1-mysql.sql
> +--
2.6.1-mysql.sql/2.6.1-oracle is prepared for the next version, but 2.6.0-to-2.6.1 help users upgrade 2.6.1 from 2.6.0

2023-08-16 00:48 UTC, moremind commented
sorry, my means is error, you must add it in init sql

2023-08-16 00:50 UTC, moremind commented
> sorry, my means make a mistake, you must add it in init sql

why need isBlank?

2023-08-16 01:01 UTC, kerwin612 commented
> > sorry, my means make a mistake, you must add it in init sql
> 
> why need isBlank?  

With isBlank, I can do something when the parameter doesn't contain special field.

2023-08-16 01:10 UTC, moremind submitted a review, later dismissed

2023-08-17 01:43 UTC, moremind commented
you need to add the field in opengauss database

2023-08-17 02:19 UTC, moremind commented
> you need to add the field in opengauss database

need 2.6.0-2.6.1-og.sql

2023-08-17 02:28 UTC, moremind approved these changes

2023-08-17 03:14 UTC, merged