add oracle e2e test script
apache/shenyu pull request #5304
Opened 2023-11-15 15:13 UTC by zzzk1

[Task] e2e test script for oracle #5302 

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

2023-11-16 01:09 UTC, moremind commented
not right

2023-11-20 13:24 UTC, moremind commented
pls add right script and yaml

2023-11-21 13:08 UTC, zzzk1 commented
Okay, I think I know how to do this

2023-11-21 16:00 UTC, moremind requested changes

2023-11-21 16:00 UTC, moremind commented on shenyu-e2e/shenyu-e2e-case/k8s/shenyu-oracle.yml
> +          image: registry.aliyuncs.com/helowin/oracle_11g
use docker hub images?

2023-11-21 16:00 UTC, moremind commented on shenyu-e2e/script/storage_init_oracle.sh
> +mkdir -p /tmp/shenyu-e2e/driver/oracle
add license header

2023-11-22 08:33 UTC, moremind commented
may you refer to: #5309

2023-11-22 09:49 UTC, closed without merging