test client grpc test case
apache/shenyu pull request #5395
Opened 2024-01-03 14:54 UTC by zzzk1

[Task] shenyu-client-grpc test case #4545

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

2024-01-17 14:05 UTC, dragon-zhang requested changes
The coverage of testing needs to be improved

2024-01-24 01:31 UTC, moremind commented
pls add my wechat: yijia1949

2024-01-24 05:17 UTC, moremind approved these changes

2024-01-26 01:33 UTC, dragon-zhang approved these changes

2024-01-26 08:42 UTC, merged