[type:feat]add rocketmq logging e2e test
apache/shenyu pull request #5439
Opened 2024-02-06 04:00 UTC by xcsnx

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

2024-03-27 11:13 UTC, moremind requested changes

2024-03-27 11:13 UTC, moremind commented on .github/workflows/e2e-k8s.yml
> -      - master
not change this

2024-03-27 11:13 UTC, moremind commented on .github/workflows/e2e-k8s.yml
> +    if: (github.repository == 'xcsnx/shenyu' && ${{ needs.changes.outputs.e2e == 'true' }})
not change this

2024-03-27 11:13 UTC, moremind commented on .github/workflows/e2e-k8s.yml
> +    if: (github.repository == 'xcsnx/shenyu' && ${{ needs.changes.outputs.e2e == 'true' }})
not change this

2024-03-27 11:13 UTC, moremind commented on .github/workflows/e2e-k8s.yml
> +        uses: mxschmitt/action-tmate@v3
comment this

2024-04-01 13:01 UTC, moremind requested changes

2024-04-01 13:01 UTC, moremind commented on shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-http/k8s/rocket-mq.yml
> +            - name: NAMESRV_ADDR     #通过环境变量指定namesrv 地址，注意该值为namesrv svc地址
use English

2024-04-01 13:08 UTC, xcsnx commented on shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-http/k8s/rocket-mq.yml
> +            - name: NAMESRV_ADDR     #通过环境变量指定namesrv 地址，注意该值为namesrv svc地址
ok

2024-04-01 14:29 UTC, moremind requested changes

2024-04-01 14:29 UTC, moremind commented on shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-http/k8s/script/e2e-http-sync.sh
> +
remove the line

2024-04-01 14:29 UTC, moremind commented on shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-http/k8s/script/e2e-http-sync.sh
> +
remove the line

2024-04-02 09:41 UTC, moremind approved these changes

2024-04-02 09:41 UTC, merged