Export Selector Data should be combined with Discovery Data #5492
apache/shenyu pull request #5493
Opened 2024-03-16 06:09 UTC by Aias00

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

2024-03-19 07:02 UTC, moremind approved these changes

2024-03-19 07:04 UTC, moremind requested changes

2024-03-19 07:04 UTC, moremind commented on shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ConfigsExportImportController.java
> +        if (!result.getCode().equals(CommonErrorCode.SUCCESSFUL)) {
not change

2024-03-19 07:04 UTC, moremind commented on shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ConfigsExportImportController.java
> +                // sync data
should avoid npe

2024-03-19 14:23 UTC, Aias00 commented
cause i thought that the import method should keep clean，just do save data logic。 and the sync event will be done after import success

---- Replied Message ----
| From | ***@***.***> |
| Date | 03/19/2024 21:41 |
| To | apache/shenyu ***@***.***> |
| Cc | aias00 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [apache/shenyu] Export Selector Data should be combined with Discovery Data #5492 (PR #5493) |

@moremind commented on this pull request.

In shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java:

> @@ -280,7 +280,6 @@ public ConfigImportResult importData(final List<PluginDTO> pluginList) {
                 pluginId = pluginDO.getId();
                 if (pluginMapper.insertSelective(pluginDO) > 0) {
                     // publish create event. init plugin data
-                    pluginEventPublisher.onCreated(pluginDO);


why remove?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-03-20 02:31 UTC, moremind approved these changes

2024-03-20 11:38 UTC, merged

2024-03-28 13:24 UTC, ywj1352 commented
@Aias00  Can we close it now？

2024-03-28 14:11 UTC, Aias00 commented
> @Aias00 Can we close it now？

yeap, already done