[example] add WASM http client plugin example
apache/shenyu pull request #5595
Opened 2024-07-15 13:58 UTC by loongs-zhang

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

2024-07-16 10:23 UTC, moremind requested changes

2024-07-16 10:23 UTC, moremind commented on shenyu-examples/shenyu-examples-plugin-wasm/src/main/java/org/apache/shenyu/examples/plugin/wasm/RustHttpClientPlugin.java
> +        return PluginEnum.NETTY_HTTP_CLIENT.getCode() - 1;
why not new plugin order?

2024-07-16 10:23 UTC, moremind commented on shenyu-examples/shenyu-examples-plugin-wasm/src/main/java/org/apache/shenyu/examples/plugin/wasm/RustHttpClientPlugin.java
> +        return "rustHttpClient";
create RustHttpClient

2024-07-18 12:44 UTC, loongs-zhang commented
Flopped

2024-07-18 12:44 UTC, closed without merging